insert into breeds
(description,
image_url,
max_life_span,
min_life_span,
name, size,
trainability)
VALUES
('Pyrenean Mastiff coats are solid or pied pattern and come in a variety of colors. Notable color patters are white and beige, white and black, white and brown, white and silver, and many more!',
'https://a-z-animals.com/media/2022/05/pyrenean-mastiff-picture-id152940383-e1653589569893.jpg',
13,
10,
'Pyrenean Mastiff',
'LARGE',
3),
('The Great Dane was originally bred to hunt wild boar, but they probably wouldn t be very good at it today. The ferociousness necessary to track down such a large, wily animal was eventually bred out of the Great Dane.',
'https://cdn.britannica.com/60/234760-050-FD1BC47F/Harlequin-great-dane-dog.jpg',
10,
7,
'Great Dane',
'LARGE',
3),
('Unlike the Alaskan and Siberian Huskies they are descended from, Alaskan Klee Kais are meant to be companion dogs, rather than working animals that pull sleds.',
'https://dogtime.com/assets/uploads/gallery/alaskan-klee-kai-dog-breed-pictures/alaskan-klee-kai-breed-pictures-6.jpg',
16,
12,
'Alaskan Klee Kais',
'SMALL',
4
),
('The Auggie is a mixed breed dog–a cross between the Australian Shepherd and Corgi, and typically, the Miniature Australian Shepherd and the Pembroke Welsh Corgi.',
'https://dogtime.com/assets/uploads/gallery/auggie-mixed-dog-breed-pictures/auggie-mixed-dog-breed-pictures-1.jpg',
15,
12,
'Auggie',
'MEDIUM',
4),
('The Borador is a mixed breed dog. They are not purebreds like their Border Collie or Labrador Retriever parents.',
'https://dogtime.com/assets/uploads/gallery/borador-mixed-dog-breed-pictures/borador-mixed-dog-breed-pictures-2.jpg',
15,
10,
'Borador',
'LARGE',
3),
('The Bordoodle is a mixed breed dog. They are not purebreds like their Border Collie or Poodle parents.',
'https://dogtime.com/assets/uploads/gallery/bordoodle-mixed-dog-breed-pictures/bordoodle-mixed-dog-breed-pictures-2.jpg',
15,
12,
'Bordoodle',
'LARGE',
3);